### ISSUE TITLE
Unable to run application after updating to v3.0.0

### ISSUE THREAD

**Issue by kishangohel** [embrace-io/embrace-flutter-sdk#10]
**Description**
After upgrading to v3.0.0 iPhoneX (iOS 16.7.10) not able to run the application.
Same code working for all iOS 17

**Error Logs**
lldb) dyld[1985]: Symbol not found: _swift_getTypeByMangledNameInContext2
  Referenced from: <BAF91B53-6D8B-3AEB-B6C8-3737C61371FD> /private/var/containers/Bundle/Application/E1D34753-2E6B-4198-9E77-B93B4C7777EE/Runner.app/Frameworks/EmbraceCaptureService.framework/EmbraceCaptureService (built for iOS 17.2 which is newer than running OS)
  Expected in:     <5F6B7D24-C88A-3199-87CF-560C1B7A4C6D> /usr/lib/swift/libswiftCore.dylib
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001d9448ee4 dyld`__abort_with_payload + 8
dyld`__abort_with_payload:
->  0x1d9448ee4 <+8>:  b.lo   0x1d9448f00               ; <+36>
    0x1d9448ee8 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1d9448eec <+16>: mov    x29, sp
    0x1d9448ef0 <+20>: bl     0x1d93ebea0               ; cerror_nocancel
Target 0: (Runner) stopped.

**Expected Behavior**
It should run on older iOS OS version

**Screenshots**
N/A

**Additional Context**
* Embrace Flutter SDK version: 3.0.0
* Dart version: 3.5.3
* Flutter version: 3.24.3
* Xcode: 16.0
* CocoaPods version: 1.15.2
* Android version(s):
* iOS/tvOS version(s): 16.7.10

**Comment by eliabsisay** [comment]
Hi @hespert-fx - Thanks for submitting this issue. A member of the team will take a look and get back to you shortly.

**Comment by kishangohel** [comment]
@eliabsisay any update?

**Comment by fractalwrench** [comment]
@kishangohel this has been fixed in 3.0.1. Please ping me if you have any further questions.

**Comment by kishangohel** [comment]
@fractalwrench still not able to run app with version 3.0.1
No Build errors
Device: iPhone 7 Plus
OS: iOS 15.8.3

Logs from xcode
warning: (arm64) /Users/XXX/Library/Developer/Xcode/DerivedData/Runner-cjbajnzinrfdprannbzsaphrqgpn/Build/Products/Debug-dev-iphoneos/Runner.app/Runner empty dSYM file detected, dSYM was created with an executable with no debug info.
dyld[866]: Symbol not found: (_objc_claimAutoreleasedReturnValue)
  Referenced from: '/private/var/containers/Bundle/Application/9D2F5BE3-6739-4927-B706-614A7B6EE77B/Runner.app/Frameworks/KSCrashCore.framework/KSCrashCore'
  Expected in: '/usr/lib/libobjc.A.dylib'

**Comment by fractalwrench** [comment]
Sorry to hear that @kishangohel - I'll pass this onto our iOS engineers who will be in touch if they need further information.

**Comment by kishangohel** [comment]
@fractalwrench any update, please?

**Comment by eliabsisay** [comment]
@kishangohel - its in the current sprint for the iOS team. A team member will be in touch if they have any questions.

**Comment by kishangohel** [comment]
@eliabsisay can you please provide any tentative date

**Comment by eliabsisay** [comment]
@kishangohel - we just released Flutter 3.1 which has the update - can you please test and confirm if its resolved your issue?

**Comment by kishangohel** [comment]
@eliabsisay now I can run as well as archive app
